Fix parseImage function to correctly set registries
adevinta/noe pull request #102
Opened 2024-03-20 17:23 UTC by carlosrejano

# Context:
  We detected that proxies were not correctly been used by `noe`. We
  found some issues in the `parseImage` function:
  - the registry had to literally match so if you had a proxy set for `docker.io` registry if it used `something.docker.io` it would not replace with the proxy.
  - It did not stop after finding the relevant proxy, this lead to tests correctly passing without showing issues.

  # What does this PR?
  - Add regex so it matches all subdomains of proxy registry domain.
  - Stops looking for proxies once it finds one.
  - Fix the relevant tests so it tests more cases.

2024-03-20 17:30 UTC, scaldarola approved these changes

2024-03-20 18:28 UTC, tjamet requested changes

2024-03-20 18:28 UTC, tjamet commented on pkg/registry/registry.go
> +		if ok, err := filepath.Match("*."+proxy.Registry, registry); err == nil && ok {
I am unsure we should march registry subdomains.
I think the mentioned `something.docker.io` references `registry-1.docker.io` which is [added within noe](https://github.com/adevinta/noe/blob/89411cd31af1b048d0b9d49a16d123132999714c/pkg/registry/registry.go#L451), so [do other registry clients like containerd](https://github.com/containerd/containerd/blob/124456ef83f5984e597c4ab2b48b9074199c1aa0/core/remotes/docker/registry.go#L193)

2024-03-21 09:04 UTC, carlosrejano commented
Closing it since this approach is not desired.

2024-03-21 09:04 UTC, closed without merging